# base config using pretrained CoNNear cochlea features

data_root: ./data/
train_list_file: ./data/training_list.txt
val_list_file: ./data/validation_list.txt
test_list_file: ./data/testing_list.txt
label_map: ./data/label_map.json

exp:
    trackio: False
    trackio_space_id:
    trackio_server_url:
    proj_name: torch-kwt-connear-base
    exp_dir: ./runs
    exp_name: exp-connear-base-0.0.1
    device: auto
    log_freq: 20
    log_to_file: True
    log_to_stdout: True
    warm_cache: False
    val_freq: 5
    n_workers: 0
    pin_memory: True
    cache: 2
    feature_cache: True
    feature_cache_dir: ./data/.feature_cache_connear_base

hparams:
    seed: 0
    precision: bfloat16 # one of float32, bfloat16, or float16
    batch_size: 16
    grad_accum_steps: 16
    n_epochs: 250
    l_smooth: 0.1

    audio:
        feature_type: connear
        feature_time_bins: 128
        sr: 16000
        n_mels: 40
        n_fft: 480
        win_length: 480
        hop_length: 160
        coch_env_sr: 100
        coch_filter_n: 38
        coch_low_freq: 50.0
        coch_high_freq: 8000.0
        connear_weights_path: ./data/connear/Gmodel.pt
        connear_auto_download: False
        connear_device: auto
        connear_sr: 20000
        connear_batch_size: 32
        connear_n_channels: 198
        connear_log_scale: 1000000.0
        connear_normalize: True
        connear_input_scale: 1.0
        cache_log_every: 1000

    model:
        name:
        input_res: [198, 128]
        patch_res: [3, 4]
        num_classes: 35
        mlp_dim: 512
        dim: 192
        heads: 4
        depth: 10
        dim_head: 48
        dropout: 0.05
        emb_dropout: 0.1
        pre_norm: True
        use_sdpa: True
        use_helion_kernels: True

    optimizer:
        opt_type: adamw_fused
        opt_kwargs:
          lr: 0.0005
          weight_decay: 0.1

    scheduler:
        n_warmup: 0
        max_epochs: 250
        scheduler_type: one_cycle_lr
        max_lr: 0.0005
        pct_start: 0.1
        div_factor: 25.0
        final_div_factor: 10000.0
        anneal_strategy: cos

    augment:
        resample:
            r_min: 0.85
            r_max: 1.15

        time_shift:
            s_min: -0.1
            s_max: 0.1

        bg_noise:
            bg_folder: ./data/_background_noise_/

        spec_aug:
            n_time_masks: 2
            time_mask_width: 32
            n_freq_masks: 2
            freq_mask_width: 12
