# sample config using pretrained CoNNear cochlea features

data_root: ./data/
train_list_file: ./data/training_list.txt
val_list_file: ./data/validation_list.txt
test_list_file: ./data/testing_list.txt
label_map: ./data/label_map.json

exp:
    trackio: False
    trackio_space_id:
    trackio_server_url:
    proj_name: torch-kwt-connear
    exp_dir: ./runs
    exp_name: exp-connear-0.0.1
    device: auto
    log_freq: 20
    log_to_file: True
    log_to_stdout: True
    warm_cache: False
    val_freq: 5
    n_workers: 0
    pin_memory: True
    cache: 2
    feature_cache: True
    feature_cache_dir: ./data/.feature_cache_connear

hparams:
    seed: 0
    batch_size: 512
    grad_accum_steps: 1
    n_epochs: 140
    l_smooth: 0.1

    audio:
        feature_type: connear
        feature_time_bins: 98
        sr: 16000
        n_mels: 40
        n_fft: 480
        win_length: 480
        hop_length: 160
        coch_env_sr: 100
        coch_filter_n: 38
        coch_low_freq: 50.0
        coch_high_freq: 8000.0
        connear_weights_path: ./data/connear/Gmodel.pt
        connear_auto_download: False
        connear_device: auto
        connear_sr: 20000
        connear_batch_size: 4
        connear_n_channels: 40
        connear_log_scale: 1000000.0
        connear_normalize: True
        connear_input_scale: 1.0

    model:
        name:
        input_res: [40, 98]
        patch_res: [40, 1]
        num_classes: 35
        mlp_dim: 256
        dim: 64
        heads: 1
        depth: 12
        dropout: 0.0
        emb_dropout: 0.1
        pre_norm: False
        use_sdpa: True
        use_helion_kernels: False

    optimizer:
        opt_type: adamw
        opt_kwargs:
          lr: 0.001
          weight_decay: 0.1

    scheduler:
        n_warmup: 10
        max_epochs: 140
        scheduler_type: cosine_annealing

    augment:
        resample:
            r_min: 0.85
            r_max: 1.15

        time_shift:
            s_min: -0.1
            s_max: 0.1

        bg_noise:
            bg_folder: ./data/_background_noise_/

        spec_aug:
            n_time_masks: 2
            time_mask_width: 25
            n_freq_masks: 2
            freq_mask_width: 7
