# -*- coding: utf-8 -*-
"""test carfac model to extract cochleagram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P-7aySpfXaoiOMLCbrpC-KPDwJvQzKEr
"""

! pip -q install "carfac @ git+https://github.com/google/carfac.git@master#subdirectory=python"
! pip -q install librosa soundfile

from google.colab import files

uploaded = files.upload()
audio_path = next(iter(uploaded.keys()))
print(audio_path)

import librosa
import numpy as np

TARGET_SR = 16_000

x, sr = librosa.load(audio_path, sr=TARGET_SR, mono=True)
x = x.astype(np.float32)

# Optional but usually useful for experiments
x = x / (np.max(np.abs(x)) + 1e-9)

print(x.shape, sr)

from carfac.np import carfac

cfp = carfac.design_carfac(fs=TARGET_SR, n_ears=1)

cfp = carfac.carfac_init(cfp)

naps, cfp, bm, seg_ohc, seg_agc = carfac.run_segment(cfp, x)

print("n_ch:", cfp.n_ch)
print("NAP shape:", naps.shape)

nap = naps[:, :, 0]  # [time, channels] = [samples, 65]

features_mean = nap.mean(axis=0)
features_std = nap.std(axis=0)
features_max = nap.max(axis=0)

features = np.concatenate([
    features_mean,
    features_std,
    features_max,
])

print(features.shape)  # 65 * 3 = 195

frame_size = int(0.010 * TARGET_SR)  # 160 samples at 16 kHz
num_frames = len(nap) // frame_size

nap_trimmed = nap[:num_frames * frame_size]
nap_frames = nap_trimmed.reshape(num_frames, frame_size, cfp.n_ch)

frame_features = nap_frames.mean(axis=1)  # [frames, 65]

print(frame_features.shape)

import numpy as np
import matplotlib.pyplot as plt

nap = naps[:, :, 0]  # [time_samples, carfac_channels]

# Pool raw sample-level NAP into 10 ms frames
frame_ms = 10
frame_size = int(TARGET_SR * frame_ms / 1000)

num_frames = nap.shape[0] // frame_size
nap_trimmed = nap[:num_frames * frame_size]

# [frames, frame_size, channels] -> [frames, channels]
nap_frames = nap_trimmed.reshape(num_frames, frame_size, cfp.n_ch).mean(axis=1)

# Compress dynamic range for visualization
Z = np.log1p(np.maximum(nap_frames, 0)).T  # [channels, frames]

times = np.arange(num_frames) * frame_ms / 1000

plt.figure(figsize=(14, 5))
plt.imshow(
    Z,
    aspect="auto",
    origin="upper",
    extent=[times[0], times[-1], cfp.n_ch - 1, 0],
)
plt.colorbar(label="log(1 + NAP)")
plt.xlabel("Time, seconds")
plt.ylabel("CARFAC channel")
plt.title("CARFAC NAP / cochleogram")
plt.show()

freqs = np.asarray(cfp.pole_freqs)

plt.figure(figsize=(14, 5))
plt.imshow(
    Z,
    aspect="auto",
    origin="upper",
    extent=[times[0], times[-1], freqs[-1], freqs[0]],
)
plt.colorbar(label="log(1 + NAP)")
plt.xlabel("Time, seconds")
plt.ylabel("Approx. center frequency, Hz")
plt.title("CARFAC NAP / cochleogram")
plt.show()

plt.figure(figsize=(14, 4))

for ch in [0, 10, 25, 40, 64]:
    if ch < cfp.n_ch:
        plt.plot(times, nap_frames[:, ch], label=f"ch {ch}, ~{cfp.pole_freqs[ch]:.0f} Hz")

plt.xlabel("Time, seconds")
plt.ylabel("NAP")
plt.title("Selected CARFAC channel activations")
plt.legend()
plt.show()